apiVersion: v1
kind: Service
metadata:
  {{- if .Values.global.enableAwsAlb.enabled }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
  {{- end }}
  name: coffee
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "http"
    port: {{ .Values.coffee.port }}
    targetPort: {{ .Values.coffee.targetPort }}
  selector:
    app: coffee-server
status:
  loadBalancer: {}
