apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: coffee-worker-deployment
  name: coffee-worker
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.coffee_worker.replicaCount }}
  serviceName: coffee
  selector:
    matchLabels:
      app: coffee-worker
  template:
    metadata:
      labels:
        app: coffee-worker
    spec:
      serviceAccountName: flash-coffee
{{ if .Values.global.nodeSelectors.enabled }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: {{ .Values.global.nodeSelectors.label }}
                  operator: In
                  values:
                    - {{ .Values.global.nodeSelectors.other }}
{{ end }}
{{ if .Values.global.taints.enabled}}
      tolerations:
      - key: dedicated
        operator: Equal
        value: {{ .Values.global.taints.other }}
        effect: NoSchedule
{{ end }}   
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      {{ if .Values.useSecret }}
      imagePullSecrets:
        - name: {{ required "pullSecretName is required" .Values.pullSecretName }}
      {{ end }}
      initContainers:
      - name: check-redis
        image: {{ .Values.global.toolbox.image.repository }}:{{ .Values.global.toolbox.image.tag }}
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - until redis-cli -h {{ .Values.global.environment.redis_host }} ping; do echo "waiting for {{ .Values.global.environment.redis_host }}"; sleep 1;
          done;
      - name: check-postgres
        image: {{ .Values.global.toolbox.image.repository }}:{{ .Values.global.toolbox.image.tag }}
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: postgres_host
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: database_url
        command: ['sh', '-c',
          'until pg_isready -h $(POSTGRES_HOST) -p {{ .Values.global.environment.postgres_port}} -d $(DATABASE_URL);
          do echo waiting for database; sleep 1; done;']
      volumes:
        {{ if .Values.global.sharedSecretName }}
        - name: sharedcert
          secret:
            secretName: {{ .Values.global.sharedSecretName }}
        {{ end }}
      containers:
        - args:
          - scheduler
          env:
          - name: CONFIG_HASH
            value: {{ include "flash-coffee.confighash" . | quote }}
          - name: PYTHONUNBUFFERED
            value: "0"
          - name: COOKIE_SECRET
            value: d84c0edd-ab5e-4664-b0ee-2cd15a9ae5f0 
          - name: QUEUES
            value: queries,scheduled_queries,celery
          - name: LOG_LEVEL
            value: ERROR
          {{ if .Values.global.environment.parent_host }}  
          - name: PARENT_HOST
            value: {{ .Values.global.environment.parent_host }}
          {{ end }}
          {{ if .Values.global.domain }}  
          - name: HOST
            value: {{.Values.global.domain}}
          {{ end }}
          - name: MY_APP_NAME
            value: coffee-worker
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP                
          {{ if .Values.global.environment.cluster_id }}  
          - name: MY_CLUSTER_ID
            value: {{ .Values.global.environment.cluster_id }}
          {{ end }} 
          - name: LOGIQ_FLASH_HOST
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: logiq_flash_host
          - name: LOGIQ_FLASH_PORT
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: logiq_flash_port
          - name: WORKERS_COUNT
            value: "{{ .Values.coffee_worker.replicaCount }}"
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: redis_host
          - name: REDIS_URL
            value: redis://{{.Values.global.environment.redis_host}}:{{ .Values.global.environment.redis_port}}/0
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: postgres_password
          - name: POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: postgres_host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: postgres_port
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: postgres_db
          - name: POSTGRES_COFFEE_DB
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: postgres_coffee_db
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: coffee_database_url
          - name: S3_URL
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: s3_url
          - name: S3_ACCESS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.sharedSecretName  }}
                key: s3_access
          - name: S3_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.sharedSecretName  }}
                key: s3_secret
          - name: S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.global.sharedSecretName  }}
                key: s3_bucket
          {{ if .Values.global.environment.admin_name }}
          - name: ADMIN_NAME
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: admin_name
          {{ end }}
          {{ if .Values.global.environment.admin_password }}
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: admin_password
          {{ end }}
          {{ if .Values.global.environment.admin_org }}
          - name: ADMIN_ORG
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: admin_org
          {{ end }}
          {{ if .Values.global.environment.admin_email }}
          - name: ADMIN_EMAIL
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: admin_email
          {{ end }}
          {{ if .Values.global.environment.mail_server }}
          - name: MAIL_SERVER
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: mail_server
          {{ end }}
          {{ if .Values.global.environment.mail_port }}
          - name: MAIL_PORT
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: mail_port
          {{ end }}
          {{ if .Values.global.environment.mail_username }}
          - name: MAIL_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: mail_username
          {{ end }}
          {{ if .Values.global.environment.mail_password }}
          - name: MAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: mail_password
          {{ end }}
          {{ if .Values.global.environment.mail_default_sender }}
          - name: MAIL_DEFAULT_SENDER
            valueFrom:
              secretKeyRef:
                name: {{ template "flash-coffee.fullname" . }}
                key: mail_default_sender
          {{ end }}
          {{ if .Values.global.chart.prometheus }}
          - name: PROM_ALERT_MGR_URL
            value: {{ .Release.Name }}-prometheus-alertmanager:9093
          {{ end }} 
          - name: EVENT_REPORTING_WEBHOOKS
            value: ""
          - name: LOGIQ_AUDIT_EVENT_GROUP
            value: logiq-audit
          volumeMounts:
          {{ if .Values.global.sharedSecretName }}
          - mountPath: /app/sharedcerts
            name: sharedcert
          {{ end }}
          image: "{{ .Values.coffee_worker.image.repository }}:{{ .Values.coffee_worker.image.tag }}"
          imagePullPolicy: {{ .Values.coffee_worker.image.pullPolicy}}
          name: coffee-worker
          {{- if .Values.coffee_worker.resources }}
          resources: {{- toYaml .Values.coffee_worker.resources | nindent 12 }}
          {{- end }}
      restartPolicy: Always
