apiVersion: v1
kind: Service
metadata:
  name: ssr-report-gen
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "http"
    port: {{ .Values.ssr_report_gen.port }}
    targetPort: {{ .Values.ssr_report_gen.targetPort }}
  selector:
    app: ssr-report-gen
status:
  loadBalancer: {}
