# Cluster role which grants access to the default pod security policy
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flash-coffee
  namespace: {{ .Release.Namespace }}
  labels:
    app: flash-coffee
rules:
- apiGroups:
  - policy
  resourceNames:
  - flash-coffee
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - extensions
  resourceNames:
  - flash-coffee
  resources:
  - podsecuritypolicies
  verbs:
  - use