{{- if and .Values.cnpg.enabled .Values.cnpg.createSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cnpg.superuserSecret.name }}
  namespace: {{ default .Release.Namespace .Values.cnpg.namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.cnpg.superuserSecret.username | quote }}
  password: {{ .Values.cnpg.superuserSecret.password | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cnpg.appUserSecret.name }}
  namespace: {{ default .Release.Namespace .Values.cnpg.namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.cnpg.appUserSecret.username | quote }}
  password: {{ .Values.cnpg.appUserSecret.password | quote }}
{{- end }}
{{- if and .Values.cnpg.enabled .Values.cnpg.migration.enabled (not .Values.cnpg.migration.source.passwordSecret.enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-cnpg-migration-source" (include "logiq.fullname" .) }}
  namespace: {{ default .Release.Namespace .Values.cnpg.namespace }}
type: Opaque
stringData:
  password: {{ .Values.cnpg.migration.source.password | quote }}
{{- end }}
