{{- if eq (.Values.cnpg.enabled | toString) "true" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cnpg.superuserSecret.name }}
  namespace: {{ default .Release.Namespace .Values.cnpg.namespaceOverride }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.cnpg.superuserSecret.username | quote }}
  password: {{ .Values.cnpg.superuserSecret.password | quote }}
{{- end }}
