{{- if .Values.cnpg.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cnpg.superuserSecret.name }}
  namespace: {{ default .Release.Namespace .Values.cnpg.namespaceOverride }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.cnpg.superuserSecret.username | quote }}
  password: {{ .Values.cnpg.superuserSecret.password | quote }}
{{- if and (eq .Values.cnpg.mode "recovery") (eq .Values.cnpg.recovery.method "import") .Values.cnpg.recovery.import.source.passwordSecret.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cnpg.recovery.import.source.passwordSecret.name }}
  namespace: {{ default .Release.Namespace .Values.cnpg.namespaceOverride }}
type: Opaque
stringData:
  {{ .Values.cnpg.recovery.import.source.passwordSecret.key }}: {{ required "cnpg.recovery.import.source.passwordSecret.value is required when mode is recovery and method is import." .Values.cnpg.recovery.import.source.passwordSecret.value | quote }}
{{- end }}
{{- end }}
