{{- if .Values.envoyGateway.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-gateway-helm-envoy-gateway-rolebinding" .Release.Name }}
  labels:
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: envoy-gateway
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.envoyGateway.controller.clusterRoleName | default "eg-gateway-helm-envoy-gateway-role" }}
{{- end }}
