{{- if .Values.envoyGateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/version: v1.6.0
    control-plane: envoy-gateway
    helm.sh/chart: apica-ascent-{{ .Chart.Version }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: gateway-helm
      control-plane: envoy-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "19001"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: gateway-helm
        control-plane: envoy-gateway
    spec:
      serviceAccountName: envoy-gateway
      containers:
        - name: envoy-gateway
          image: {{ .Values.envoyGateway.controller.image | default "docker.io/envoyproxy/gateway:v1.6.0" }}
          imagePullPolicy: {{ .Values.envoyGateway.controller.imagePullPolicy | default "IfNotPresent" }}
          args:
            - server
            - --config-path=/config/envoy-gateway.yaml
          env:
            - name: ENVOY_GATEWAY_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ .Values.envoyGateway.controller.clusterDomain | default "cluster.local" }}
          ports:
            - containerPort: 18000
              name: grpc
              protocol: TCP
            - containerPort: 18001
              name: ratelimit
              protocol: TCP
            - containerPort: 18002
              name: wasm
              protocol: TCP
            - containerPort: 19001
              name: metrics
              protocol: TCP
            - containerPort: 9443
              name: webhook
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml (.Values.envoyGateway.controller.resources | default (dict "limits" (dict "memory" "1Gi") "requests" (dict "cpu" "100m" "memory" "256Mi"))) | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /config
              name: envoy-gateway-config
              readOnly: true
            - mountPath: /certs
              name: certs
              readOnly: true
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 10
      volumes:
        - name: envoy-gateway-config
          configMap:
            name: envoy-gateway-config
        - name: certs
          secret:
            secretName: envoy-gateway
{{- end }}
