{{- if .Values.envoyGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: envoy-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/version: v1.6.0
    control-plane: envoy-gateway
    helm.sh/chart: apica-ascent-{{ .Chart.Version }}
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: gateway-helm
    control-plane: envoy-gateway
  ports:
    - name: grpc
      port: 18000
      protocol: TCP
      targetPort: 18000
    - name: ratelimit
      port: 18001
      protocol: TCP
      targetPort: 18001
    - name: wasm
      port: 18002
      protocol: TCP
      targetPort: 18002
    - name: metrics
      port: 19001
      protocol: TCP
      targetPort: 19001
    - name: webhook
      port: 9443
      protocol: TCP
      targetPort: 9443
{{- end }}
