{{- if .Values.envoyGateway.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-gateway-helm-leader-election-rolebinding" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/version: v1.6.0
    helm.sh/chart: apica-ascent-{{ .Chart.Version }}
subjects:
  - kind: ServiceAccount
    name: envoy-gateway
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-gateway-helm-leader-election-role" .Release.Name }}
{{- end }}
