{{- if .Values.envoyGateway.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: envoy-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gateway-helm
    app.kubernetes.io/version: v1.6.0
    helm.sh/chart: apica-ascent-{{ .Chart.Version }}
{{- end }}
