{{- if .Values.perfectscale.enabled }}
---
apiVersion: perfectscale.io/v1
kind: WorkloadAutomationConfig
metadata:
  name: coffe-worker-automation
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    kind: StatefulSet
    name: coffe-worker
  automation:
    operational:
      automationMode: "Enabled"
    containers:
      coffee-worker:
        operational:
          restrictions:
            cpuManagement:
              request:
                increaseEnabled: true
                decreaseEnabled: true
                minimumCores: -1
                maximumCores: 2
              limit:
                keepLimit: false
            memoryManagement:
              request:
                minimumGiB: -1
                maximumGiB: 8
              limit:
                increaseEnabled: true
                decreaseEnabled: true
                minimumGiB: -1
                maximumGiB: 8
                memoryLeakDetection:
                  maxMemoryIncreaseIterations:
                    daily: 3
                    weekly: 6
      ssr-report-gen:
        operational:
          restrictions:
            cpuManagement:
              request:
                increaseEnabled: true
                decreaseEnabled: true
                minimumCores: -1
                maximumCores: 2
              limit:
                keepLimit: false
            memoryManagement:
              request:
                minimumGiB: -1
                maximumGiB: 8
              limit:
                increaseEnabled: true
                decreaseEnabled: true
                minimumGiB: -1
                maximumGiB: 8
                memoryLeakDetection:
                  maxMemoryIncreaseIterations:
                    daily: 3
                    weekly: 6
{{- end }}
