{{- $existing := lookup "v1" "Secret" .Release.Namespace .Values.global.sharedSecretName -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.global.sharedSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "logiq.name" . }}
    helm.sh/chart: {{ template "logiq.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-1"
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{- if and $existing (index $existing.data "tls.crt") (index $existing.data "tls.key") }}
  tls.crt: {{ index $existing.data "tls.crt" }}
  tls.key: {{ index $existing.data "tls.key" }}
{{- else if or
  (empty .Values.global.environment.internal_cert_crt)
  (empty .Values.global.environment.internal_cert_key)
}}
{{ ( include "logiq.gen-certs" . ) | indent 2 }}
{{- else }}
  tls.crt: {{ .Values.global.environment.internal_cert_crt }}
  tls.key: {{ .Values.global.environment.internal_cert_key }}
{{- end }}
  awsaccesskey: {{ if .Values.global.environment.AWS_ACCESS_KEY_ID }}{{ .Values.global.environment.AWS_ACCESS_KEY_ID | b64enc | quote }}{{ else }}{{ randAlphaNum 20 | b64enc | quote }}{{ end }}
  awssecretkey: {{ if .Values.global.environment.AWS_SECRET_ACCESS_KEY }}{{ .Values.global.environment.AWS_SECRET_ACCESS_KEY | b64enc | quote }}{{ else }}{{ randAlphaNum 40 | b64enc | quote }}{{ end }}
  s3_access: {{ if .Values.global.environment.s3_access }}{{ .Values.global.environment.s3_access | b64enc | quote }} {{ end }}
  s3_secret: {{ if .Values.global.environment.s3_secret }}{{ .Values.global.environment.s3_secret | b64enc | quote }} {{ end }}
  s3_bucket: {{ if .Values.global.environment.s3_bucket }}{{ .Values.global.environment.s3_bucket | b64enc | quote }} {{ end }}
