apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.global.sharedSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "logiq.name" . }}
    helm.sh/chart: {{ template "logiq.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "logiq.gen-certs" . ) | indent 2 }}
  awsaccesskey: {{ if .Values.global.environment.AWS_ACCESS_KEY_ID }}{{ .Values.global.environment.AWS_ACCESS_KEY_ID | b64enc | quote }}{{ else }}{{ randAlphaNum 20 | b64enc | quote }}{{ end }}
  awssecretkey: {{ if .Values.global.environment.AWS_SECRET_ACCESS_KEY }}{{ .Values.global.environment.AWS_SECRET_ACCESS_KEY | b64enc | quote }}{{ else }}{{ randAlphaNum 40 | b64enc | quote }}{{ end }}
  s3_access: {{ if .Values.global.environment.s3_access }}{{ .Values.global.environment.s3_access | b64enc | quote }} {{ end }}
  s3_secret: {{ if .Values.global.environment.s3_secret }}{{ .Values.global.environment.s3_secret | b64enc | quote }} {{ end }}
  s3_bucket: {{ if .Values.global.environment.s3_bucket }}{{ .Values.global.environment.s3_bucket | b64enc | quote }} {{ end }}
