{{- if not .Values.vault.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: ascentSecrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "logiq.name" . }}
    helm.sh/chart: {{ template "logiq.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ ( include "logiq.gen-certs" . ) | indent 2 }}
  admin_email: {{ if .Values.global.environment.s3_bucket }}{{ .Values.global.environment.s3_bucket | b64enc | quote }} {{ end }}
  admin_name: {{ if .Values.global.environment.s3_bucket }}{{ .Values.global.environment.s3_bucket | b64enc | quote }} {{ end }}
  admin_org: {{ if .Values.global.environment.s3_bucket }}{{ .Values.global.environment.s3_bucket | b64enc | quote }} {{ end }}
  admin_password: {{ if .Values.global.environment.s3_bucket }}{{ .Values.global.environment.s3_bucket | b64enc | quote }} {{ end }}
  coffee_database_url: postgresql://postgres:postgres@postgres:5432/coffee
  database_url: postgresql://postgres:postgres@postgres:5432/postgres
  flash_host: {{ if .Values.global.environment.flash_host }}{{ .Values.global.environment.flash_host | b64enc | quote }} {{ end }}
  flash_port: {{ if .Values.global.environment.flash_port }}{{ .Values.global.environment.flash_port | b64enc | quote }} {{ end }}
  mail_default_sender: {{ if .Values.global.environment.mail_default_sender }}{{ .Values.global.environment.mail_default_sender | b64enc | quote }} {{ end }}
  mail_password: {{ if .Values.global.environment.mail_password }}{{ .Values.global.environment.mail_password | b64enc | quote }} {{ end }}
  mail_port: {{ if .Values.global.environment.mail_port }}{{ .Values.global.environment.mail_port | b64enc | quote }} {{ end }}
  mail_server: {{ if .Values.global.environment.mail_server }}{{ .Values.global.environment.mail_server | b64enc | quote }} {{ end }}
  mail_username: {{ if .Values.global.environment.mail_username }}{{ .Values.global.environment.mail_username | b64enc | quote }} {{ end }}
  postgres_coffee_db: {{ if .Values.global.environment.postgres_coffee_db }}{{ .Values.global.environment.postgres_coffee_db | b64enc | quote }} {{ end }}
  postgres_db: {{ if .Values.global.environment.postgres_db }}{{ .Values.global.environment.postgres_db | b64enc | quote }} {{ end }}
  postgres_host: {{ if .Values.global.environment.postgres_host }}{{ .Values.global.environment.postgres_host | b64enc | quote }} {{ end }}
  postgres_password: {{ if .Values.global.environment.postgres_password }}{{ .Values.global.environment.postgres_password | b64enc | quote }} {{ end }}
  postgres_port: {{ if .Values.global.environment.postgres_port }}{{ .Values.global.environment.postgres_port | b64enc | quote }} {{ end }}
  postgres_user: {{ if .Values.global.environment.postgres_user }}{{ .Values.global.environment.postgres_user | b64enc | quote }} {{ end }}
  redis_host: {{ if .Values.global.environment.redis_host }}{{ .Values.global.environment.redis_host | b64enc | quote }} {{ end }}
  redis_port: {{ if .Values.global.environment.redis_port }}{{ .Values.global.environment.redis_port | b64enc | quote }} {{ end }}
  license.jws: {{ if .Values.global.environment.license.jws }}{{ .Values.global.environment.license.jws | b64enc | quote }} {{ end }}
  objstore.yml: dHlwZTogczMKcHJlZml4OiBsb2dpcS1pbnN0YXN0b3JlLW1ldHJpY3MKY29uZmlnOgoKICBhY2Nlc3Nfa2V5OiBsb2dpcV9hY2Nlc3MKICBzZWNyZXRfa2V5OiBsb2dpcV9zZWNyZXQKCiAgYnVja2V0OiBsb2dpcSAKCiAgZW5kcG9pbnQ6IHMzLWdhdGV3YXk6OTAwMCAKICBpbnNlY3VyZTogdHJ1ZQoKICByZWdpb246IHVzLWVhc3QtMSA=
---
apiVersion: v1
kind: Secret
type: kubernetes.io/Opaque
metadata:
  name: ascentSecrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "logiq.name" . }}
    helm.sh/chart: {{ template "logiq.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  s3_access: {{ if .Values.global.environment.s3_access }}{{ .Values.global.environment.s3_access | b64enc | quote }} {{ end }}
  s3_secret: {{ if .Values.global.environment.s3_secret }}{{ .Values.global.environment.s3_secret | b64enc | quote }} {{ end }}
  s3_bucket: {{ if .Values.global.environment.s3_bucket }}{{ .Values.global.environment.s3_bucket | b64enc | quote }} {{ end }}
  s3_url: {{ if .Values.global.environment.s3_url }}{{ .Values.global.environment.s3_url | b64enc | quote }} {{ end }}
  s3_region: {{ if .Values.global.environment.s3_region }}{{ .Values.global.environment.s3_region | b64enc | quote }} {{ end }}
{{- end }}
