{{- if .Values.global.chart.thanos }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.prometheus.prometheus.thanos.objectStorageConfig.secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
data:
  thanos.yaml: {{ tpl ( .Files.Get "config/thanos-config.tpl" ) . | b64enc }}
{{ end }}
