apiVersion: v1
data:
  ruler.yml: |-
    groups:
      - name: "metamonitoring"
        rules:
          - alert: "PrometheusDown"
            expr: absent(up{prometheus="{{ .Release.Namespace }}/{{ .Release.Namespace }}-prometheus-prometheus"})
kind: ConfigMap
metadata:
  name: thanos-ruler-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ template "logiq.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}

