{{- if .Values.vault.enabled }}
---
apiVersion: v1
data:
  ca.crt: {{.Values.vault.server_ca_certificate}}
kind: Secret
metadata:
  creationTimestamp: null
  name: vault-ca
  namespace: {{ .Release.Namespace }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
  namespace: {{ .Release.Namespace }}
spec:
  address: {{.Values.vault.server_address}}
  skipTLSVerify: false
  caCertSecretRef: vault-ca
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "vso-{{ .Release.Namespace }}"
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "vso-{{ .Release.Namespace }}-tokenreview"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: "vso-{{ .Release.Namespace }}"
    namespace: {{ .Release.Namespace }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vso-auth
  namespace: {{ .Release.Namespace }}
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: {{ .Values.vault.auth_mount }}
  kubernetes:
    audiences:
      - api
    role: "{{ .Release.Namespace }}_role"
    serviceAccount: "vso-{{ .Release.Namespace }}"
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  namespace: {{ .Release.Namespace }}
  name: ascent-kafka-cert
spec:
  vaultAuthRef: vso-auth
  mount: pki
  role: "{{ .Release.Namespace }}.apica.io"
  commonName: "{{ .Release.Namespace }}.apica.io"
  format: pem
  expiryOffset: 144h
  ttl: 168h
  destination:
    create: true
    name: ascent-kafka-cert
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ascentSecrets
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: "secret/ascent/{{ .Release.Namespace }}"
  path: "ascent-secrets"
  vaultAuthRef: vso-auth
  destination:
    name: ascentSecrets
    create: true
    type: kubernetes.io/tls
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ascentS3Secrets
  namespace: {{ .Release.Namespace }}
spec:
  type: kv-v2
  mount: "secret/ascent/{{ .Release.Namespace }}"
  path: "ascent-secrets"
  vaultAuthRef: vso-auth
  destination:
    name: ascentS3Secrets
    create: true
    type: kubernetes.io/Opaque
{{- end }}
