# Default values for logiqctl.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.io/logiqai/logiqctl
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  clusterIP: ~
  port: 8080
  nodePort: 318080
  portName: http

configurationFiles: true
secrets: true
podPerNode: false

## Additional Annotations for the Kubernetes Batch (uploadDashboard-job)
uploadDashboardJob:
  annotations:

resources:
  requests:
   cpu: 100m
   memory: 100Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

global:
  environment:
    upload_dashboard: false
    cluster_id: demo
  job:
    ttlSecondsAfterFinished: 100
  chart:
    prometheus: true
    postgres: true
    redis: true
    s3gateway: false
    grafana: false
    thanos: false
