# Cluster role which grants access to the default pod security policy
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: coffee-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: coffee-server
rules:
- apiGroups:
  - policy
  resourceNames:
  - coffee-server
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - extensions
  resourceNames:
  - coffee-server
  resources:
  - podsecuritypolicies
  verbs:
  - use