# Cluster role binding for default pod security policy granting all authenticated users access
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coffee-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: coffee-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: coffee-server
subjects:
- kind: ServiceAccount
  name: coffee-server
  namespace: {{ .Release.Namespace }}