# Cluster role which grants access to the default pod security policy
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: s3-gateway-job
  namespace: {{ .Release.Namespace }}
  labels:
    app: s3-gateway-job
rules:
- apiGroups:
  - policy
  resourceNames:
  - s3-gateway-job
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - extensions
  resourceNames:
  - s3-gateway-job
  resources:
  - podsecuritypolicies
  verbs:
  - use