{{- if and (.Values.gcsgateway.enabled) (.Values.gcsgateway.fileJson ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "minio.fullname" . }}-gcp
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
    {{ (.Files.Glob "gcs_key.json").AsSecrets | indent 2 }}
{{- end -}}