apiVersion: v1
kind: Secret
metadata:
  name: {{ template "minio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ template "minio.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  accesskey: {{ if .Values.global.environment.s3_access }}{{ .Values.global.environment.s3_access | b64enc | quote }}{{ else }}{{ randAlphaNum 20 | b64enc | quote }}{{ end }}
  secretkey: {{ if .Values.global.environment.s3_secret }}{{ .Values.global.environment.s3_secret | b64enc | quote }}{{ else }}{{ randAlphaNum 40 | b64enc | quote }}{{ end }}
  {{ if .Values.global.environment.AWS_ACCESS_KEY_ID }}
  awsaccesskey: {{ .Values.global.environment.AWS_ACCESS_KEY_ID | b64enc | quote }}
  {{ end }}
  {{ if .Values.global.environment.AWS_SECRET_ACCESS_KEY }}
  awssecretkey: {{ .Values.global.environment.AWS_SECRET_ACCESS_KEY | b64enc | quote }}
  {{ end }}
  {{- if .Values.gcsgateway.enabled }}
  {{- if .Values.gcsgateway.encodedJson }}
  gcs_key.json: {{ .Values.gcsgateway.encodedJson }}
  {{- else if .Values.gcsgateway.fileJson }}
  gcs_key.json: {{ (.Files.Get "gcs_key.json") |  b64enc}}
  {{- else }}
  gcs_key.json: {{ .Values.gcsgateway.gcsKeyJson | b64enc }}
  {{- end }}
  {{- end }}
  {{ if .Values.tls.enabled }}
  mchosttarget: {{ printf "https://%s:%s@%s:%d" .Values.global.environment.s3_access .Values.global.environment.s3_secret (include "minio.fullname" .) (int64 .Values.service.port) | b64enc | quote }}
  {{ else }}
  mchosttarget: {{ printf "http://%s:%s@%s:%d" .Values.global.environment.s3_access .Values.global.environment.s3_secret (include "minio.fullname" .) (int64 .Values.service.port) | b64enc | quote }}
  {{ end }}
