apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "logiq-flash.name" . }}
    chart: {{ template "logiq-flash.chart" . }}
    heritage: {{ .Release.Service }}
  name: {{ template "logiq-flash.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "logiq-flash.fullname" . }}
subjects:
- kind: ServiceAccount
  name: logiq-flash
  namespace: {{ .Release.Namespace }}
