apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "logiq-flash.fullname" . }}
  labels:
    app: {{ template "logiq-flash.name" . }}
    chart: {{ template "logiq-flash.chart" . }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
