# Cluster role which grants access to the default pod security policy
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logiq-flash
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "logiq-flash.name" . }}
rules:
- apiGroups:
  - policy
  resourceNames:
  - logiq-flash
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - extensions
  resourceNames:
  - logiq-flash
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - tcproutes
  - udproutes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
