{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "logiq-flash.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "logiq-flash.name" . }}
    chart: {{ template "logiq-flash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  postgres_port: {{ if .Values.global.environment.postgres_port }}{{ .Values.global.environment.postgres_port | b64enc | quote }} {{ end }}
  postgres_host: {{ if .Values.global.environment.postgres_host }}{{ .Values.global.environment.postgres_host | b64enc | quote }} {{ end }}
  postgres_password: {{ if .Values.global.environment.postgres_password }}{{ .Values.global.environment.postgres_password | b64enc | quote }} {{ end }}
  postgres_db: {{ if .Values.global.environment.postgres_db }}{{ .Values.global.environment.postgres_db | b64enc | quote }} {{ end }}
  postgres_user: {{ if .Values.global.environment.postgres_user }}{{ .Values.global.environment.postgres_user | b64enc | quote }} {{ end }}
  redis_host: {{ if .Values.global.environment.redis_host }}{{ .Values.global.environment.redis_host | b64enc | quote }} {{ end }}
  redis_port: {{ if .Values.global.environment.redis_port }}{{ .Values.global.environment.redis_port | toString | b64enc | quote }} {{ end }}
  admin_email: {{ if .Values.global.environment.admin_email }}{{ .Values.global.environment.admin_email | b64enc | quote }}{{ end }}
  admin_password: {{ if .Values.global.environment.admin_password }}{{ .Values.global.environment.admin_password | b64enc | quote }}{{ end }}
{{- end }}
