{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "logiq-flash.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "logiq-flash.name" . }}
    chart: {{ template "logiq-flash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  postgres_port: {{ if .Values.global.environment.postgres_port }}{{ .Values.global.environment.postgres_port | b64enc | quote }} {{ end }}
  postgres_host: {{ if .Values.global.environment.postgres_host }}{{ .Values.global.environment.postgres_host | b64enc | quote }} {{ end }}
  postgres_password: {{ if .Values.global.environment.postgres_password }}{{ .Values.global.environment.postgres_password | b64enc | quote }} {{ end }}
  postgres_db: {{ if .Values.global.environment.postgres_db }}{{ .Values.global.environment.postgres_db | b64enc | quote }} {{ end }}
  postgres_user: {{ if .Values.global.environment.postgres_user }}{{ .Values.global.environment.postgres_user | b64enc | quote }} {{ end }}
  redis_host: {{ if .Values.global.environment.redis_host }}{{ .Values.global.environment.redis_host | b64enc | quote }} {{ end }}
  redis_port: {{ if .Values.global.environment.redis_port }}{{ .Values.global.environment.redis_port | toString | b64enc | quote }} {{ end }}
  admin_email: {{ if .Values.global.environment.admin_email }}{{ .Values.global.environment.admin_email | b64enc | quote }}{{ end }}
  admin_password: {{ if .Values.global.environment.admin_password }}{{ .Values.global.environment.admin_password | b64enc | quote }}{{ end }}
{{- end }}

---
{{- if .Values.kafkaSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Namespace }}-ascent-kafka-cert
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: secret-sync
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: kafka-tls
    app: {{ template "logiq-flash.name" . }}
    chart: {{ template "logiq-flash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  certificate: {{ .Values.global.environment.kafka_certificate | default "" | b64enc | quote }}
  private_key: {{ .Values.global.environment.kafka_private_key | default "" | b64enc | quote }}
  ca_chain: {{ .Values.global.environment.kafka_ca_chain | default "" | b64enc | quote }}
  issuing_ca: {{ .Values.global.environment.kafka_issuing_ca | default "" | b64enc | quote }}
  serial_number: {{ .Values.global.environment.kafka_serial_number | default "" | b64enc | quote }}
  private_key_type: {{ .Values.global.environment.kafka_private_key_type | default "" | b64enc | quote }}
  expiration: {{ .Values.global.environment.kafka_expiration | default "" | b64enc | quote }}
{{- end }}

