apiVersion: v1
kind: Service
metadata:
  name: {{ template "logiq-flash.name" . }}-ml
  namespace: {{ .Release.Namespace }}
  {{- if .Values.global.enableAwsAlb.enabled }}
  annotations:
     alb.ingress.kubernetes.io/healthcheck-path: /ready
     alb.ingress.kubernetes.io/healthcheck-port: "8080"
  {{- end }}
  labels:
    app: {{ template "logiq-flash.name" . }}-ml
    chart: {{ template "logiq-flash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    promMonitor: {{ template "logiq-flash.name" . }}
spec:
  clusterIP: None
  type: ClusterIP
  ports:
    - port: {{ .Values.tracingui.port }}
      targetPort: 16686
      protocol: TCP
      name: {{ .Values.tracingui.name }}
    - port: {{ .Values.grpc.port }}
      targetPort: 50054
      protocol: TCP
      name: {{ .Values.grpc.name }}
    - port: {{ .Values.webcli.port }}
      targetPort: {{ .Values.webcli.port }}
      protocol: TCP
      name: {{ .Values.webcli.name }}
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
      protocol: TCP
      name: {{ .Values.api.name }}
    - port: {{ .Values.liveness_port.port }}
      targetPort: {{ .Values.liveness_port.port }}
      protocol: TCP
      name: {{ .Values.liveness_port.name }}
  selector:
    app: {{ template "logiq-flash.name" . }}-ml
    release: {{ .Release.Name }}
