{{- if .Values.global.environment.upload_dashboard }}
{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "logiqctl.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "logiqctl.name" . }}
    chart: {{ template "logiqctl.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  admin_email: {{ if .Values.global.environment.admin_email }}{{ .Values.global.environment.admin_email | b64enc | quote }}{{ else }}{{ randAlphaNum 20 | b64enc | quote }}{{ end }}
  admin_password: {{ if .Values.global.environment.admin_password }}{{ .Values.global.environment.admin_password | b64enc | quote }}{{ else }}{{ randAlphaNum 40 | b64enc | quote }}{{ end }}
  admin_name: {{ if .Values.global.environment.admin_name }}{{ .Values.global.environment.admin_name | b64enc | quote }}{{ else }}{{ randAlphaNum 20 | b64enc | quote }}{{ end }}
  admin_org: {{ if .Values.global.environment.admin_org }}{{ .Values.global.environment.admin_org | b64enc | quote }}{{ else }}{{ randAlphaNum 40 | b64enc | quote }}{{ end }}
{{- end }}
{{- end }}
