{{- if .Values.global.environment.upload_dashboard }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logiqctl
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "logiqctl.name" . }}
{{- end }}
