apiVersion: v2
version: 4.0.0
appVersion: v2.16.7
description: Apica Ascent - Cloud-native observability platform
keywords:
  - apica
  - ascent
  - observability
  - logging
  - monitoring
  - tracing
  - metrics
  - gateway-api
  - envoy-gateway
annotations:
  category: Observability
  licenses: Apache-2.0
dependencies:
  - alias: cnpg
    condition: cnpg.enabled
    name: cluster
    repository: https://cloudnative-pg.github.io/charts
    version: 0.6.1
  - name: flash-coffee
    version: 1.0.0
    condition: global.chart.flash-coffee
  - name: logiq-flash
    version: 1.0.0
    condition: global.chart.logiq-flash
  - name: logiqctl
    version: 1.0.0
    condition: global.chart.logiqctl
  - name: flash-discovery
    version: 1.0.0
    condition: global.chart.flash-discovery
  - name: valkey
    condition: global.chart.redis
    repository: https://valkey.io/valkey-helm
    version: 0.9.0
    alias: redis
  - name: thanos
    condition: global.chart.thanos
    repository: oci://ghcr.io/thanos-community/helm-charts
    version: 0.18.0
home: https://apica.io
sources:
  - https://github.com/apica-io/apica-ascent-helm
icon: https://www.apica.io/wp-content/uploads/2023/01/apica-logo-white-2022.png
maintainers:
  - email: eric.sproul@apica.io
    name: esproul
  - email: kumar.vishnu@apica.io
    name: vishnu
  - email: lokesh.sm@apica.io
    name: lokesh
  - email: manchal.sharma@apica.io
    name: manchal
  - email: support@apica.io
    name: support
name: apica-ascent
type: application
kubeVersion: ">=1.24.0-0"
