on:
  push:
    branches:
    - 'master'
    paths-ignore:
    - '*.tgz'
    - 'github-markdown.css'
    - 'index.*'
    - 'README.md'

jobs:
  trigger-ci:
    runs-on: ubuntu-latest
      steps:
      - name: Trigger Helm deploy test
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{ "ref": "${{ github.ref }}", "commit": "${{ github.sha }}", "pusher": "${{ github.actor }}" }' \
            "${{ secrets.JENKINS_URL }}/generic-webhook-trigger/invoke?token=${{ secrets.CI_WEBHOOK_TOKEN }}"
